sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
before_script:
  - npm prune
  - npm i -g cypress-cli
script:
  - npm test
  - cypress ci
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
